audio:
  device: ''
commentary:
  analyst_silence_threshold: 5
  mode: reflex_analyst
  writer_update_rate: 1
gemini:
  api_key: ''
  model: gemini-2.5-flash-native-audio-preview-12-2025
  sample_rate: 24000
ssl:
  gc_addr: 224.5.23.1
  gc_port: 11003
  our_team_color: blue
  our_team_name: ibis
  tracker_addr: 224.5.23.2
  tracker_port: 11010
