# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ssl_vision_detection_tracked.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ssl_vision_detection_tracked.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_gc_common_pb2 as ssl__gc__common__pb2
import ssl_gc_geometry_pb2 as ssl__gc__geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ssl_vision_detection_tracked.proto\x12\x0brobocup_ssl\x1a\x13ssl_gc_common.proto\x1a\x15ssl_gc_geometry.proto\"g\n\x0bTrackedBall\x12!\n\x03pos\x18\x01 \x02(\x0b\x32\x14.robocup_ssl.Vector3\x12!\n\x03vel\x18\x02 \x01(\x0b\x32\x14.robocup_ssl.Vector3\x12\x12\n\nvisibility\x18\x03 \x01(\x02\"\xd3\x01\n\nKickedBall\x12!\n\x03pos\x18\x01 \x02(\x0b\x32\x14.robocup_ssl.Vector2\x12!\n\x03vel\x18\x02 \x02(\x0b\x32\x14.robocup_ssl.Vector3\x12\x17\n\x0fstart_timestamp\x18\x03 \x02(\x01\x12\x16\n\x0estop_timestamp\x18\x04 \x01(\x01\x12&\n\x08stop_pos\x18\x05 \x01(\x0b\x32\x14.robocup_ssl.Vector2\x12&\n\x08robot_id\x18\x06 \x01(\x0b\x32\x14.robocup_ssl.RobotId\"\xba\x01\n\x0cTrackedRobot\x12&\n\x08robot_id\x18\x01 \x02(\x0b\x32\x14.robocup_ssl.RobotId\x12!\n\x03pos\x18\x02 \x02(\x0b\x32\x14.robocup_ssl.Vector2\x12\x13\n\x0borientation\x18\x03 \x02(\x02\x12!\n\x03vel\x18\x04 \x01(\x0b\x32\x14.robocup_ssl.Vector2\x12\x13\n\x0bvel_angular\x18\x05 \x01(\x02\x12\x12\n\nvisibility\x18\x06 \x01(\x02\"\xe8\x01\n\x0cTrackedFrame\x12\x14\n\x0c\x66rame_number\x18\x01 \x02(\r\x12\x11\n\ttimestamp\x18\x02 \x02(\x01\x12\'\n\x05\x62\x61lls\x18\x03 \x03(\x0b\x32\x18.robocup_ssl.TrackedBall\x12)\n\x06robots\x18\x04 \x03(\x0b\x32\x19.robocup_ssl.TrackedRobot\x12,\n\x0bkicked_ball\x18\x05 \x01(\x0b\x32\x17.robocup_ssl.KickedBall\x12-\n\x0c\x63\x61pabilities\x18\x06 \x03(\x0e\x32\x17.robocup_ssl.Capability*\x92\x01\n\nCapability\x12\x16\n\x12\x43\x41PABILITY_UNKNOWN\x10\x00\x12\"\n\x1e\x43\x41PABILITY_DETECT_FLYING_BALLS\x10\x01\x12$\n CAPABILITY_DETECT_MULTIPLE_BALLS\x10\x02\x12\"\n\x1e\x43\x41PABILITY_DETECT_KICKED_BALLS\x10\x03\x42\x41Z?github.com/RoboCup-SSL/ssl-game-controller/internal/app/tracker')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssl_vision_detection_tracked_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/RoboCup-SSL/ssl-game-controller/internal/app/tracker'
  _globals['_CAPABILITY']._serialized_start=839
  _globals['_CAPABILITY']._serialized_end=985
  _globals['_TRACKEDBALL']._serialized_start=95
  _globals['_TRACKEDBALL']._serialized_end=198
  _globals['_KICKEDBALL']._serialized_start=201
  _globals['_KICKEDBALL']._serialized_end=412
  _globals['_TRACKEDROBOT']._serialized_start=415
  _globals['_TRACKEDROBOT']._serialized_end=601
  _globals['_TRACKEDFRAME']._serialized_start=604
  _globals['_TRACKEDFRAME']._serialized_end=836
# @@protoc_insertion_point(module_scope)
