#!/usr/bin/env python3
# Copyright (c) 2026 ibis-ssl
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

"""AI Activity Session Log Analyzer.

Reads an AI activity log (JSONL) generated by AiActivityLogger, analyzes turns,
transcriptions, tool calls, interruptions, and checks for commentary rule compliance.
"""

import argparse
import glob
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional


def find_latest_session_log(log_dir: str = "logs/ai") -> Optional[Path]:
    """Find the most recently modified non-empty session JSONL file."""
    pattern = os.path.join(log_dir, "ai_session_*.jsonl")
    files = [Path(p) for p in glob.glob(pattern)]
    if not files:
        return None
    # Filter files that have content
    non_empty = [f for f in files if f.stat().st_size > 0]
    if not non_empty:
        files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        return files[0]
    non_empty.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return non_empty[0]


def split_sentences(text: str) -> List[str]:
    """Split Japanese text into sentences."""
    if not text:
        return []
    # Split on period, exclamation, question mark, or newlines
    parts = re.split(r"(?<=[。！？\n])", text)
    return [p.strip() for p in parts if p.strip()]


def inspect_turn_compliance(turn: Dict[str, Any]) -> List[str]:
    """Check commentary compliance issues for a single turn."""
    issues = []
    full_text = turn.get("transcription", "")
    event_type = turn.get("event_type", "")
    trigger = turn.get("trigger", "")

    if not full_text and turn.get("status") != "cancelled":
        # initial_contextやteam_updateは発話を伴わないシステム設定送信のためスキップ
        if trigger in ("initial_context", "team_update"):
            return []
        # Maybe no response or only tool calls
        if not turn.get("tool_calls"):
            issues.append("発話テキストなし（無応答の可能性）")
        return issues

    sentences = split_sentences(full_text)
    sentence_count = len(sentences)

    # Rule 6: 1ターンあたり2〜3文以内（実況モードは原則1〜2文）
    if trigger == "reflex" and sentence_count > 2:
        issues.append(f"文数過多（実況モードで{sentence_count}文。原則1〜2文）")
    elif sentence_count > 3:
        issues.append(f"文数過多（{sentence_count}文。最大2〜3文）")

    # Rule 3: 自己言及禁止
    meta_phrases = ["実況に入り", "実況します", "実況を開始", "解説に入り", "解説します", "解説モード", "AIとして"]
    for phrase in meta_phrases:
        if phrase in full_text:
            issues.append(f"自己言及の疑い（'{phrase}' を含む）")

    # Rule 4: 問いかけ禁止
    question_phrases = ["いかがでしょうか", "どうでしょうか", "いかがですか", "どう思いますか", "でしょうか？"]
    for phrase in question_phrases:
        if phrase in full_text:
            issues.append(f"問いかけの疑い（'{phrase}' を含む）")

    # Rule 7: 判定確定前の断定禁止 (POSSIBLE_GOAL)
    if event_type == "POSSIBLE_GOAL":
        premature_assertions = ["外れ", "枠を外れ", "ノーゴール", "無得点", "入りません"]
        for phrase in premature_assertions:
            if phrase in full_text:
                issues.append(f"審議中における勝手な断定の疑い（'{phrase}' を含む）")

    # 感情的な絶叫表現の抑制
    emotional_phrases = ["おおっと", "うわー", "すごい！", "なんと！", "信じられません"]
    for phrase in emotional_phrases:
        if phrase in full_text:
            issues.append(f"感情的・絶叫調表現の疑い（'{phrase}' を含む）")

    # Tool call errors
    for tc in turn.get("tool_calls", []):
        if tc.get("status") == "error":
            issues.append(f"ツールコールエラー: {tc.get('name')} ({tc.get('error')})")

    return issues


def parse_session_file(file_path: Path) -> Dict[str, Any]:
    """Parse JSONL session file into structured session data."""
    session_info: Dict[str, Any] = {
        "file": str(file_path),
        "session_id": None,
        "model": None,
        "voice": None,
        "turns": {},
        "records": [],
    }

    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except Exception:
                continue

            session_info["records"].append(record)
            event = record.get("event")

            if event == "session_start":
                session_info["session_id"] = record.get("session_id")
                session_info["model"] = record.get("model")
                session_info["voice"] = record.get("voice")
                session_info["thinking_level"] = record.get("thinking_level")

            elif event == "prompt_sent":
                t_id = record.get("turn_id")
                if t_id:
                    session_info["turns"].setdefault(t_id, {
                        "turn_id": t_id,
                        "trigger": record.get("trigger"),
                        "event_type": record.get("event_type"),
                        "priority": record.get("priority"),
                        "payload": record.get("payload"),
                        "sent_at": record.get("ts"),
                        "thoughts": [],
                        "transcriptions": [],
                        "tool_calls": [],
                        "status": "in_progress",
                    })

            elif event == "thought":
                t_id = record.get("turn_id")
                if t_id and t_id in session_info["turns"]:
                    session_info["turns"][t_id]["thoughts"].append(record.get("thought", ""))

            elif event == "transcription":
                t_id = record.get("turn_id")
                if t_id and t_id in session_info["turns"]:
                    session_info["turns"][t_id]["transcriptions"].append(record.get("text", ""))

            elif event == "tool_call":
                t_id = record.get("turn_id")
                if t_id and t_id in session_info["turns"]:
                    session_info["turns"][t_id]["tool_calls"].append({
                        "call_id": record.get("call_id"),
                        "name": record.get("tool_name"),
                        "latency_ms": record.get("latency_ms"),
                        "status": record.get("status"),
                        "error": record.get("error"),
                        "result_summary": record.get("result_summary"),
                    })

            elif event == "utterance":
                t_id = record.get("turn_id")
                if t_id and t_id in session_info["turns"]:
                    turn = session_info["turns"][t_id]
                    turn["transcription"] = record.get("transcription", "")
                    turn["audio_total_duration_ms"] = record.get("audio_total_duration_ms", 0)
                    turn["audio_played_duration_ms"] = record.get("audio_played_duration_ms", 0)
                    turn["completion_rate"] = record.get("completion_rate", 1.0)
                    turn["status"] = record.get("status")
                    turn["interrupted_reason"] = record.get("interrupted_reason")
                    turn["played_text_estimate"] = record.get("played_text_estimate", "")
                    turn["latency_to_first_audio_ms"] = record.get("latency_to_first_audio_ms")

    # Finalize transcription: if empty or missing but transcription chunks arrived, use accumulated chunks
    for t_id, turn in session_info["turns"].items():
        accumulated = "".join(turn.get("transcriptions", [])).strip()
        if (not turn.get("transcription")) and accumulated:
            turn["transcription"] = accumulated
            if not turn.get("played_text_estimate"):
                turn["played_text_estimate"] = accumulated

    return session_info


def print_report(session_info: Dict[str, Any], verbose: bool = False) -> None:
    """Format and print an evaluation report to stdout."""
    turns = session_info["turns"]
    total_turns = len(turns)

    print("=" * 80)
    print(f" AI Activity Session Report: {Path(session_info['file']).name}")
    print("=" * 80)
    print(f"Session ID    : {session_info.get('session_id') or 'N/A'}")
    print(f"Model         : {session_info.get('model') or 'N/A'}")
    print(f"Voice / Level : {session_info.get('voice')} / {session_info.get('thinking_level')}")
    print(f"Total Turns   : {total_turns}")
    print("-" * 80)

    if total_turns == 0:
        print("有効なターン記録が見つかりませんでした。")
        return

    completed_count = 0
    interrupted_count = 0
    total_latency = 0
    latency_count = 0
    all_issues = []

    for idx, (t_id, turn) in enumerate(turns.items(), 1):
        status = turn.get("status", "unknown")
        if status == "completed":
            completed_count += 1
        elif "interrupted" in status:
            interrupted_count += 1

        ttfb = turn.get("latency_to_first_audio_ms")
        if ttfb is not None:
            total_latency += ttfb
            latency_count += 1

        issues = inspect_turn_compliance(turn)
        if issues:
            all_issues.append((t_id, issues))

        # Turn header
        trig = turn.get("trigger", "")
        ev = turn.get("event_type", "")
        prio = turn.get("priority", 1)
        comp_rate = turn.get("completion_rate", 1.0)
        dur_total = turn.get("audio_total_duration_ms", 0) / 1000.0
        dur_played = turn.get("audio_played_duration_ms", 0) / 1000.0

        status_str = f"[{status.upper()}]"
        if "interrupted" in status:
            status_str = f"[{status.upper()} ({int(comp_rate * 100)}%再生: {dur_played:.1f}s/{dur_total:.1f}s, 原因: {turn.get('interrupted_reason')})]"

        print(f"\nTurn #{idx:02d} | ID: {t_id} | Trigger: {trig} | Event: {ev} (prio={prio})")
        print(f"Status        : {status_str} | TTFB: {ttfb} ms" if ttfb is not None else f"Status        : {status_str}")

        text = turn.get("transcription", "")
        played = turn.get("played_text_estimate", "")
        if text:
            print(f"Transcription : \"{text}\"")
            if played and played != text:
                print(f"Played Est.   : \"{played}\"")
        else:
            print("Transcription : (なし)")

        # Thoughts
        if verbose and turn.get("thoughts"):
            thought_full = "".join(turn["thoughts"]).strip()
            if thought_full:
                print(f"Thought       : {thought_full[:200]}..." if len(thought_full) > 200 else f"Thought       : {thought_full}")

        # Tool calls
        tool_calls = turn.get("tool_calls", [])
        if tool_calls:
            for tc in tool_calls:
                tc_status = tc.get("status")
                tc_lat = tc.get("latency_ms")
                tc_name = tc.get("name")
                tc_err = f" ERROR: {tc.get('error')}" if tc.get("error") else ""
                print(f"Tool Call     : {tc_name} [{tc_status}] ({tc_lat} ms){tc_err}")
                if verbose and tc.get("result_summary"):
                    print(f"  Result      : {str(tc['result_summary'])[:150]}")

        # Issues
        if issues:
            for iss in issues:
                print(f"  [WARNING] {iss}")

    print("\n" + "=" * 80)
    print(" SUMMARY STATISTICS")
    print("=" * 80)
    avg_ttfb = (total_latency / latency_count) if latency_count > 0 else 0
    print(f"Completed Turns   : {completed_count}/{total_turns} ({completed_count/total_turns*100:.1f}%)")
    print(f"Interrupted Turns : {interrupted_count}/{total_turns} ({interrupted_count/total_turns*100:.1f}%)")
    print(f"Average TTFB      : {avg_ttfb:.1f} ms (measured in {latency_count} turns)")
    print(f"Turns with Issues : {len(all_issues)}/{total_turns}")

    if all_issues:
        print("\n検出されたルール遵守の課題一覧:")
        for t_id, iss_list in all_issues:
            for iss in iss_list:
                print(f" - [{t_id}] {iss}")
    else:
        print("\n全てのターンが主要な実況ルール・品質基準を満たしています。")
    print("=" * 80 + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze AI session logs for SSL auto streamer.")
    parser.add_argument("log_file", nargs="?", default=None, help="Path to ai_session_*.jsonl file")
    parser.add_argument("--log-dir", default="logs/ai", help="Directory containing AI session logs")
    parser.add_argument("-v", "--verbose", action="store_true", help="Print full thoughts and tool outputs")

    args = parser.parse_args()

    if args.log_file:
        target_path = Path(args.log_file)
    else:
        target_path = find_latest_session_log(args.log_dir)

    if not target_path or not target_path.exists():
        print(f"Error: Log file not found: {target_path}", file=sys.stderr)
        sys.exit(1)

    session_info = parse_session_file(target_path)
    print_report(session_info, verbose=args.verbose)


if __name__ == "__main__":
    main()
